### ISSUE TITLE
[Bug 🐞]: Parts not showing up in game

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/LithobrakeExplorationTechnologies#106]
### Brief description of your issue

[Flipper028](https://forum.kerbalspaceprogram.com/index.php?/profile/208053-flipper028/)[](https://forum.kerbalspaceprogram.com/index.php?/profile/208053-flipper028/)
![](https://kerbal-forum-uploads.s3.us-west-2.amazonaws.com/set_resources_17/84c1e40ea0e759e3f1505eb1788ddf3c_default_photo.png)

(https://forum.kerbalspaceprogram.com/index.php?/topic/206860-1123-lithobrake-exploration-technologies-let-version-0500-adoption-land-boldly-and-safely-return-10-feb-2022/#elControls_4111913_menu)

I installed 0.5 from curse and I cannot find the parts anywhere in game. Digging into logs i find this for each part.

```
[LOG 13:57:48.395] PartLoader: Compiling Part 'LithobrakeExplorationTechnologies/Parts/Pods/LETpod2m4k/LETpod2m4k'
[ERR 13:57:48.395] PartCompiler: Cannot clone model 'NecroBones/LithobrakeExplorationTechnologies/Assets/Pods/LETpod2m4k' as model does not exist

[ERR 13:57:48.396] PartCompiler: Model was not compiled correctly

[ERR 13:57:48.397] PartCompiler: Cannot compile model

[ERR 13:57:48.398] PartCompiler: Cannot compile part
```

### Steps to reproduce

install mod

### Expected behavior

parts to show up

### Actual behavior

parts are not showing up

### Environment

```shell
latest from CurseForge
```

### How did you download and install this?

CurseForge (download and manual installation)

**Comment by Lafayette028** [comment]
[KSP.log](https://github.com/zer0Kerbal/LithobrakeExplorationTechnologies/files/8428984/KSP.log)

starts around line 17214

**Comment by zer0Kerbal** [comment]
as I suspected: the mod is installed into the wrong directory.

I suspect (according to the logs) that it is installed into:
<KSP Root>/GameData/LithobrakeExplorationTechnologies/

and it should be installed into:
<KSP Root>/NecroBones/LithobrakeExplorationTechnologies/

```
494 [LOG 13:57:01.067] Load(Texture): LithobrakeExplorationTechnologies/Assets/Bays/LETbayAtlas1-Specular
17179 [LOG 13:57:48.338] PartLoader: Compiling Part 'LithobrakeExplorationTechnologies/Parts/Bays/LETbay2mExp/LETbay2mExp'
17180 [ERR 13:57:48.342] PartCompiler: Cannot clone model 'NecroBones/LithobrakeExplorationTechnologies/Assets/Bays/LETbay2mExp' as model does not exist
```

**Comment by zer0Kerbal** [comment]
I will be dropping a new version hopefully later today/tomorrow because I found some duplicated files thanks to you.

In that version I will be including the following file:
https://github.com/zer0Kerbal/LithobrakeExplorationTechnologies/blob/0.5.1.0-prerelease/ManualInstallation.md
